version: 2

sources:
  - name: orders
    database: DEFAULT
    schema: PUBLIC
    tables:
      - name: OLIST_CUSTOMERS_DATASET
      - name: OLIST_GEOLOCATION_DATASET
      - name: OLIST_ORDERS_DATASET
      - name: OLIST_ORDER_ITEMS_DATASET
      - name: OLIST_ORDER_PAYMENTS_DATASET
      - name: OLIST_ORDER_REVIEWS_DATASET
      - name: OLIST_PRODUCTS_DATASET
      - name: OLIST_SELLERS_DATASET
      - name: PRODUCT_CATEGORY_NAME_TRANSLATION
